# Generated by Django 4.0.1 on 2022-01-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('product_image', models.ImageField(blank=True, default='products/user-default.png', null=True, upload_to='products/')),
                ('price', models.FloatField()),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
